name: Lint

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Black Version
        uses: psf/black@stable
        with:
          options: "--version"
      - name: Black Check
        uses: psf/black@stable

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: "src/python/synthterrain tests/python"
